name: generate-contribution-snake

on:
  schedule:
    - cron: "0 0 * * *"   # corre todos os dias Ã  meia-noite (UTC)
  workflow_dispatch:       # permite correr manualmente
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate snake
        uses: Platane/snk@v3
        with:
          github_user_name: miguelac4
          outputs: |
            dist/snake.svg

      - name: Commit and push snake.svg
        run: |
          mkdir -p output
          cp dist/snake.svg output/github-contribution-grid-snake.svg
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add output/github-contribution-grid-snake.svg
          git commit -m "chore: update snake animation" || echo "no changes"
          git push
